# Generated by Django 6.0.4 on 2026-04-10 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_elective', models.CharField(blank=True, choices=[('RURAL', 'Rural Banking'), ('HRM', 'Human Resources Management'), ('IT_DB', 'Information Technology & Digital Banking'), ('RISK', 'Risk Management'), ('CENTRAL', 'Central Banking')], max_length=100, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(choices=[('ABM', 'Advanced Bank Management'), ('BFM', 'Bank Financial Management'), ('ABFM', 'Advanced Business & Financial Management'), ('BRBL', 'Banking Regulations and Business Laws'), ('ELECTIVE', 'Elective Paper')], max_length=20)),
                ('current_score', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.candidate')),
            ],
            options={
                'unique_together': {('candidate', 'paper_code')},
            },
        ),
        migrations.CreateModel(
            name='SRSMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('interval', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review', models.DateTimeField()),
                ('repetition_count', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
            ],
            options={
                'unique_together': {('candidate', 'card_id')},
            },
        ),
    ]
