# Generated by Django 6.0.4 on 2026-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidate_last_study_date_candidate_study_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
