# Generated by Django 6.0.4 on 2026-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidate_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperprogress',
            name='paper_code',
            field=models.CharField(max_length=20),
        ),
    ]
