# Generated by Django 6.0.4 on 2026-04-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_paperprogress_paper_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bite_id', models.CharField(max_length=50, unique=True)),
                ('paper_code', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('concept', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('formula', models.CharField(blank=True, max_length=300)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('numerical', 'Numerical')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=200)),
                ('tolerance', models.FloatField(default=0.0)),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('bite_type', models.CharField(choices=[('conceptual', 'Conceptual'), ('numerical', 'Numerical'), ('regulatory', 'Regulatory')], default='conceptual', max_length=20)),
                ('estimated_minutes', models.IntegerField(default=5)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['paper_code', 'module', 'bite_id'],
            },
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='session',
        ),
        migrations.CreateModel(
            name='BiteAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('bite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bite')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bite_attempts', to='api.candidate')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
    ]
