# Generated by Django 6.0.4 on 2026-04-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bite_remove_questionattempt_session_biteattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bite',
            name='chapter',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
