# Generated by Django 6.0.4 on 2026-04-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bite_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paper_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bundles', to='api.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='bite',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bites', to='api.marketplacebundle'),
        ),
        migrations.CreateModel(
            name='BundleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_bundles', to='api.candidate')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marketplacebundle')),
            ],
            options={
                'unique_together': {('candidate', 'bundle')},
            },
        ),
    ]
