# Generated by Django 6.0.4 on 2026-04-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_marketplacebundle_bite_bundle_bundleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='bite',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
