# Generated by Django 6.0.4 on 2026-04-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bite_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_time_spent_seconds',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='xp_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_bites_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features_json',
            field=models.JSONField(default=dict, help_text='JSON list of enabled feature flags'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.candidate'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('PRO', 'Professional'), ('ELITE', 'Elite Performance')], default='FREE', max_length=50),
        ),
    ]
