# Generated by Django 6.0.4 on 2026-04-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_candidate_total_time_spent_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srsmetadata',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('WEAK', 'Weak'), ('MASTERED', 'Mastered')], default='NEW', max_length=20),
        ),
    ]
