# Generated by Django 6.0.4 on 2026-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_srsmetadata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bite',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('numerical', 'Numerical'), ('match', 'Match the Following'), ('assertion_reason', 'Assertion-Reason'), ('fitb', 'Fill in the Blanks')], max_length=20),
        ),
    ]
